name: world_cup_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  provider:
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/data.json
